# Site settings
# in the templates available like {{ site.myvariable }}.
title: Павел Гузенко - персональный сайт художника
email: your-email@domain.com
brand: Павел Гузенко
headline: Художник, Дизайнер
description: > # this means to ignore newlines until "baseurl:"
  Павел Гузенко - персональный сайт художника
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Pavel Guzenko, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: pavelguzenko@yandex.ru
phone: +38-063-011-88-11

# Tracking
googleAnalitycsID: UA-83933844-1

